chassis_control:
  ros__parameters:
    robot:
      chassis_radius: 0.0875
      wheel_perimeter: 0.647
      fl_motor_start_angle: 0.2
      fr_motor_start_angle: 4.9
      rl_motor_start_angle: 2.7
      rr_motor_start_angle: 3.5
